//
// AwardOutcome.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AwardOutcome: Codable, JSONEncodable, Hashable {

    public var outcomeTitle: String?
    public var outcomeCategory: String?
    public var outcomeDetails: [AwardOutcomeDetail]?

    public init(outcomeTitle: String? = nil, outcomeCategory: String? = nil, outcomeDetails: [AwardOutcomeDetail]? = nil) {
        self.outcomeTitle = outcomeTitle
        self.outcomeCategory = outcomeCategory
        self.outcomeDetails = outcomeDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case outcomeTitle
        case outcomeCategory
        case outcomeDetails
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(outcomeTitle, forKey: .outcomeTitle)
        try container.encodeIfPresent(outcomeCategory, forKey: .outcomeCategory)
        try container.encodeIfPresent(outcomeDetails, forKey: .outcomeDetails)
    }
}

