//
// AwardEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AwardEvent: Codable, JSONEncodable, Hashable {

    public var eventTitle: String?
    public var eventYear: String?
    public var outcomeItems: [AwardOutcome]?

    public init(eventTitle: String? = nil, eventYear: String? = nil, outcomeItems: [AwardOutcome]? = nil) {
        self.eventTitle = eventTitle
        self.eventYear = eventYear
        self.outcomeItems = outcomeItems
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventTitle
        case eventYear
        case outcomeItems
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(eventTitle, forKey: .eventTitle)
        try container.encodeIfPresent(eventYear, forKey: .eventYear)
        try container.encodeIfPresent(outcomeItems, forKey: .outcomeItems)
    }
}

