//
// BoxOfficeWeekendData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BoxOfficeWeekendData: Codable, JSONEncodable, Hashable {

    public var items: [BoxOfficeWeekendDataDetail]?
    public var errorMessage: String?

    public init(items: [BoxOfficeWeekendDataDetail]? = nil, errorMessage: String? = nil) {
        self.items = items
        self.errorMessage = errorMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case errorMessage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
    }
}

