//
// BoxOfficeWeekendDataDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BoxOfficeWeekendDataDetail: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var rank: String?
    public var title: String?
    public var image: String?
    public var weekend: String?
    public var gross: String?
    public var weeks: String?

    public init(id: String? = nil, rank: String? = nil, title: String? = nil, image: String? = nil, weekend: String? = nil, gross: String? = nil, weeks: String? = nil) {
        self.id = id
        self.rank = rank
        self.title = title
        self.image = image
        self.weekend = weekend
        self.gross = gross
        self.weeks = weeks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case rank
        case title
        case image
        case weekend
        case gross
        case weeks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(rank, forKey: .rank)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(weekend, forKey: .weekend)
        try container.encodeIfPresent(gross, forKey: .gross)
        try container.encodeIfPresent(weeks, forKey: .weeks)
    }
}

