//
// BoxOfficeShort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BoxOfficeShort: Codable, JSONEncodable, Hashable {

    public var budget: String?
    public var openingWeekendUSA: String?
    public var grossUSA: String?
    public var cumulativeWorldwideGross: String?

    public init(budget: String? = nil, openingWeekendUSA: String? = nil, grossUSA: String? = nil, cumulativeWorldwideGross: String? = nil) {
        self.budget = budget
        self.openingWeekendUSA = openingWeekendUSA
        self.grossUSA = grossUSA
        self.cumulativeWorldwideGross = cumulativeWorldwideGross
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case budget
        case openingWeekendUSA
        case grossUSA
        case cumulativeWorldwideGross
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(budget, forKey: .budget)
        try container.encodeIfPresent(openingWeekendUSA, forKey: .openingWeekendUSA)
        try container.encodeIfPresent(grossUSA, forKey: .grossUSA)
        try container.encodeIfPresent(cumulativeWorldwideGross, forKey: .cumulativeWorldwideGross)
    }
}

