//
// CastShort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CastShort: Codable, JSONEncodable, Hashable {

    public var job: String?
    public var items: [CastShortItem]?

    public init(job: String? = nil, items: [CastShortItem]? = nil) {
        self.job = job
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case job
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(job, forKey: .job)
        try container.encodeIfPresent(items, forKey: .items)
    }
}

