//
// CastMovie.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CastMovie: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var role: String?
    public var title: String?
    public var year: String?
    public var description: String?

    public init(id: String? = nil, role: String? = nil, title: String? = nil, year: String? = nil, description: String? = nil) {
        self.id = id
        self.role = role
        self.title = title
        self.year = year
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case role
        case title
        case year
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

