//
// EpisodeShortDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EpisodeShortDetail: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var seasonNumber: String?
    public var episodeNumber: String?
    public var title: String?
    public var image: String?
    public var year: String?
    public var released: String?
    public var plot: String?
    public var imDbRating: String?
    public var imDbRatingCount: String?

    public init(id: String? = nil, seasonNumber: String? = nil, episodeNumber: String? = nil, title: String? = nil, image: String? = nil, year: String? = nil, released: String? = nil, plot: String? = nil, imDbRating: String? = nil, imDbRatingCount: String? = nil) {
        self.id = id
        self.seasonNumber = seasonNumber
        self.episodeNumber = episodeNumber
        self.title = title
        self.image = image
        self.year = year
        self.released = released
        self.plot = plot
        self.imDbRating = imDbRating
        self.imDbRatingCount = imDbRatingCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case seasonNumber
        case episodeNumber
        case title
        case image
        case year
        case released
        case plot
        case imDbRating
        case imDbRatingCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(seasonNumber, forKey: .seasonNumber)
        try container.encodeIfPresent(episodeNumber, forKey: .episodeNumber)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(released, forKey: .released)
        try container.encodeIfPresent(plot, forKey: .plot)
        try container.encodeIfPresent(imDbRating, forKey: .imDbRating)
        try container.encodeIfPresent(imDbRatingCount, forKey: .imDbRatingCount)
    }
}

