//
// ImageDataDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImageDataDetail: Codable, JSONEncodable, Hashable {

    public var title: String?
    public var image: String?

    public init(title: String? = nil, image: String? = nil) {
        self.title = title
        self.image = image
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case image
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(image, forKey: .image)
    }
}

