//
// IMDbListData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IMDbListData: Codable, JSONEncodable, Hashable {

    public var title: String?
    public var by: String?
    public var created: String?
    public var updated: String?
    public var description: String?
    public var items: [IMDbListDataDetail]?
    public var errorMessage: String?

    public init(title: String? = nil, by: String? = nil, created: String? = nil, updated: String? = nil, description: String? = nil, items: [IMDbListDataDetail]? = nil, errorMessage: String? = nil) {
        self.title = title
        self.by = by
        self.created = created
        self.updated = updated
        self.description = description
        self.items = items
        self.errorMessage = errorMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case by
        case created
        case updated
        case description
        case items
        case errorMessage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(by, forKey: .by)
        try container.encodeIfPresent(created, forKey: .created)
        try container.encodeIfPresent(updated, forKey: .updated)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
    }
}

