//
// IMDbListDataDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IMDbListDataDetail: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var index: String?
    public var title: String?
    public var fullTitle: String?
    public var year: String?
    public var image: String?
    public var imDbRating: String?
    public var imDbRatingCount: String?
    public var description: String?

    public init(id: String? = nil, index: String? = nil, title: String? = nil, fullTitle: String? = nil, year: String? = nil, image: String? = nil, imDbRating: String? = nil, imDbRatingCount: String? = nil, description: String? = nil) {
        self.id = id
        self.index = index
        self.title = title
        self.fullTitle = fullTitle
        self.year = year
        self.image = image
        self.imDbRating = imDbRating
        self.imDbRatingCount = imDbRatingCount
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case index
        case title
        case fullTitle
        case year
        case image
        case imDbRating
        case imDbRatingCount
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(index, forKey: .index)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(fullTitle, forKey: .fullTitle)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(imDbRating, forKey: .imDbRating)
        try container.encodeIfPresent(imDbRatingCount, forKey: .imDbRatingCount)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

