//
// KeywordData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KeywordData: Codable, JSONEncodable, Hashable {

    public var keyword: String?
    public var items: [MovieShort]?
    public var errorMessage: String?

    public init(keyword: String? = nil, items: [MovieShort]? = nil, errorMessage: String? = nil) {
        self.keyword = keyword
        self.items = items
        self.errorMessage = errorMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keyword
        case items
        case errorMessage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(keyword, forKey: .keyword)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
    }
}

