//
// KnownFor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct KnownFor: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var title: String?
    public var fullTitle: String?
    public var year: String?
    public var role: String?
    public var image: String?

    public init(id: String? = nil, title: String? = nil, fullTitle: String? = nil, year: String? = nil, role: String? = nil, image: String? = nil) {
        self.id = id
        self.title = title
        self.fullTitle = fullTitle
        self.year = year
        self.role = role
        self.image = image
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case fullTitle
        case year
        case role
        case image
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(fullTitle, forKey: .fullTitle)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(image, forKey: .image)
    }
}

