//
// MetacriticReviewDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MetacriticReviewDetail: Codable, JSONEncodable, Hashable {

    public var publisher: String?
    public var author: String?
    public var link: String?
    public var rate: String?
    public var content: String?

    public init(publisher: String? = nil, author: String? = nil, link: String? = nil, rate: String? = nil, content: String? = nil) {
        self.publisher = publisher
        self.author = author
        self.link = link
        self.rate = rate
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publisher
        case author
        case link
        case rate
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(publisher, forKey: .publisher)
        try container.encodeIfPresent(author, forKey: .author)
        try container.encodeIfPresent(link, forKey: .link)
        try container.encodeIfPresent(rate, forKey: .rate)
        try container.encodeIfPresent(content, forKey: .content)
    }
}

