//
// SearchResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchResult: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var resultType: String?
    public var image: String?
    public var title: String?
    public var description: String?

    public init(id: String? = nil, resultType: String? = nil, image: String? = nil, title: String? = nil, description: String? = nil) {
        self.id = id
        self.resultType = resultType
        self.image = image
        self.title = title
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case resultType
        case image
        case title
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(resultType, forKey: .resultType)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

