//
// SearchData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchData: Codable, JSONEncodable, Hashable {

    public var searchType: String
    public var expression: String
    public var results: [SearchResult]?
    public var errorMessage: String?

    public init(searchType: String, expression: String, results: [SearchResult]? = nil, errorMessage: String? = nil) {
        self.searchType = searchType
        self.expression = expression
        self.results = results
        self.errorMessage = errorMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case searchType
        case expression
        case results
        case errorMessage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(searchType, forKey: .searchType)
        try container.encode(expression, forKey: .expression)
        try container.encodeIfPresent(results, forKey: .results)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
    }
}

