//
// SimilarShort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SimilarShort: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var title: String?
    public var image: String?
    public var imDbRating: String?

    public init(id: String? = nil, title: String? = nil, image: String? = nil, imDbRating: String? = nil) {
        self.id = id
        self.title = title
        self.image = image
        self.imDbRating = imDbRating
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case image
        case imDbRating
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(imDbRating, forKey: .imDbRating)
    }
}

