//
// Top250DataDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Top250DataDetail: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var rank: String?
    public var title: String?
    public var fullTitle: String?
    public var year: String?
    public var image: String?
    public var crew: String?
    public var imDbRating: String?
    public var imDbRatingCount: String?

    public init(id: String? = nil, rank: String? = nil, title: String? = nil, fullTitle: String? = nil, year: String? = nil, image: String? = nil, crew: String? = nil, imDbRating: String? = nil, imDbRatingCount: String? = nil) {
        self.id = id
        self.rank = rank
        self.title = title
        self.fullTitle = fullTitle
        self.year = year
        self.image = image
        self.crew = crew
        self.imDbRating = imDbRating
        self.imDbRatingCount = imDbRatingCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case rank
        case title
        case fullTitle
        case year
        case image
        case crew
        case imDbRating
        case imDbRatingCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(rank, forKey: .rank)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(fullTitle, forKey: .fullTitle)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(crew, forKey: .crew)
        try container.encodeIfPresent(imDbRating, forKey: .imDbRating)
        try container.encodeIfPresent(imDbRatingCount, forKey: .imDbRatingCount)
    }
}

