//
// TvSeriesInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TvSeriesInfo: Codable, JSONEncodable, Hashable {

    public var yearEnd: String?
    public var creators: String?
    public var creatorList: [StarShort]?
    public var seasons: [String]?

    public init(yearEnd: String? = nil, creators: String? = nil, creatorList: [StarShort]? = nil, seasons: [String]? = nil) {
        self.yearEnd = yearEnd
        self.creators = creators
        self.creatorList = creatorList
        self.seasons = seasons
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case yearEnd
        case creators
        case creatorList
        case seasons
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(yearEnd, forKey: .yearEnd)
        try container.encodeIfPresent(creators, forKey: .creators)
        try container.encodeIfPresent(creatorList, forKey: .creatorList)
        try container.encodeIfPresent(seasons, forKey: .seasons)
    }
}

