//
// UsageData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsageData: Codable, JSONEncodable, Hashable {

    public var count: Int?
    public var maximum: Int?
    public var account: String?
    public var expireDate: String?
    public var errorMessage: String?

    public init(count: Int? = nil, maximum: Int? = nil, account: String? = nil, expireDate: String? = nil, errorMessage: String? = nil) {
        self.count = count
        self.maximum = maximum
        self.account = account
        self.expireDate = expireDate
        self.errorMessage = errorMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case maximum
        case account
        case expireDate
        case errorMessage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(maximum, forKey: .maximum)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encodeIfPresent(expireDate, forKey: .expireDate)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
    }
}

