//
// UserRatingDataDemographic.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserRatingDataDemographic: Codable, JSONEncodable, Hashable {

    public var allAges: UserRatingDataDemographicDetail?
    public var agesUnder18: UserRatingDataDemographicDetail?
    public var ages18To29: UserRatingDataDemographicDetail?
    public var ages30To44: UserRatingDataDemographicDetail?
    public var agesOver45: UserRatingDataDemographicDetail?

    public init(allAges: UserRatingDataDemographicDetail? = nil, agesUnder18: UserRatingDataDemographicDetail? = nil, ages18To29: UserRatingDataDemographicDetail? = nil, ages30To44: UserRatingDataDemographicDetail? = nil, agesOver45: UserRatingDataDemographicDetail? = nil) {
        self.allAges = allAges
        self.agesUnder18 = agesUnder18
        self.ages18To29 = ages18To29
        self.ages30To44 = ages30To44
        self.agesOver45 = agesOver45
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allAges
        case agesUnder18
        case ages18To29
        case ages30To44
        case agesOver45
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(allAges, forKey: .allAges)
        try container.encodeIfPresent(agesUnder18, forKey: .agesUnder18)
        try container.encodeIfPresent(ages18To29, forKey: .ages18To29)
        try container.encodeIfPresent(ages30To44, forKey: .ages30To44)
        try container.encodeIfPresent(agesOver45, forKey: .agesOver45)
    }
}

