//
// UserRatingDataDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserRatingDataDetail: Codable, JSONEncodable, Hashable {

    public var rating: String?
    public var percent: String?
    public var votes: String?

    public init(rating: String? = nil, percent: String? = nil, votes: String? = nil) {
        self.rating = rating
        self.percent = percent
        self.votes = votes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rating
        case percent
        case votes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(percent, forKey: .percent)
        try container.encodeIfPresent(votes, forKey: .votes)
    }
}

