//
// YouTubePlaylistDataItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct YouTubePlaylistDataItem: Codable, JSONEncodable, Hashable {

    public var videoId: String?
    public var title: String?
    public var description: String?
    public var duration: String?
    public var uploadDate: String?
    public var image: String?
    public var url: String?

    public init(videoId: String? = nil, title: String? = nil, description: String? = nil, duration: String? = nil, uploadDate: String? = nil, image: String? = nil, url: String? = nil) {
        self.videoId = videoId
        self.title = title
        self.description = description
        self.duration = duration
        self.uploadDate = uploadDate
        self.image = image
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case videoId
        case title
        case description
        case duration
        case uploadDate
        case image
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(videoId, forKey: .videoId)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(duration, forKey: .duration)
        try container.encodeIfPresent(uploadDate, forKey: .uploadDate)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(url, forKey: .url)
    }
}

